syntax: v1

gen:
    hooks:
        after:
            - jzero gen swagger

    split-api-types-dir: true
    # 是否生成带缓存的数据库代码
    model-mysql-cache: true
    # 是否使用远程 mysql 数据源生成代码
    model-mysql-datasource: false
    # Ignore columns while creating or updating rows, 默认为 create_at,created_at,create_time,update_at,updated_at,update_time
    model-mysql-ignore-columns: [
        "create_at","created_at","create_time","update_at","updated_at","update_time"
    ]
    # mysql 数据源配置
    model-mysql-datasource-url: "root:Admin@123@tcp(mysql:3306)/turtle_soup"
    # 使用哪些 table, 默认为 *(所有)
    model-mysql-datasource-table:
        - T_user_sessions
        - T_turtle_soup_stories
        - T_session_tokens
        - T_activity_tokens

migrate:
    database: "mysql://root:Admin@123@tcp(mysql:3306)/turtle_soup"