// Code generated by jzero. DO NOT EDIT.
package turtlesoup

import (
	"time"
)

var (
	_ = time.Now()
)

type GetActivityTokenRequest struct {
}

type GetActivityTokenResponse struct {
	Token      string `json:"token"`
	ExpireTime int64  `json:"expireTime"`
}

type GetSessionTokenRequest struct {
	ActivityToken string `json:"activityToken"`
}

type GetSessionTokenResponse struct {
	Token            string `json:"token"`
	RemainingTries   int    `json:"remainingTries"`
	RemainingAnswers int    `json:"remainingAnswers"`
	StoryID          int    `json:"storyId"`
	StoryTitle       string `json:"storyTitle"`
	Surface          string `json:"surface"`
}

type SubmitAnswerRequest struct {
	SessionToken string   `json:"sessionToken"`
	Messages     []string `json:"messages"` // 聊天记录
}

type SubmitAnswerResponse struct {
	Reply          string `json:"reply"`
	IsCorrect      bool   `json:"isCorrect"`
	RemainingTries int    `json:"remainingTries"`
	StoryAnswer    string `json:"storyAnswer,optional"`   // 仅当解答正确时返回
	NewStoryTitle  string `json:"newStoryTitle,optional"` // 仅当需要开启新故事时返回
}
