// Code generated by jzero. DO NOT EDIT.

package model

import (
	"turtle-soup/internal/model/t_activity_tokens"
	"turtle-soup/internal/model/t_session_tokens"
	"turtle-soup/internal/model/t_turtle_soup_stories"
	"turtle-soup/internal/model/t_user_sessions"

	"github.com/eddieowens/opts"
	"github.com/jzero-io/jzero-contrib/modelx"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
)

type Model struct {
	TActivityTokens    t_activity_tokens.TActivityTokensModel
	TSessionTokens     t_session_tokens.TSessionTokensModel
	TTurtleSoupStories t_turtle_soup_stories.TTurtleSoupStoriesModel
	TUserSessions      t_user_sessions.TUserSessionsModel
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {
	return Model{
		TActivityTokens:    t_activity_tokens.NewTActivityTokensModel(conn, op...),
		TSessionTokens:     t_session_tokens.NewTSessionTokensModel(conn, op...),
		TTurtleSoupStories: t_turtle_soup_stories.NewTTurtleSoupStoriesModel(conn, op...),
		TUserSessions:      t_user_sessions.NewTUserSessionsModel(conn, op...),
	}
}
